parameters:
    object_router.routing.class: Nercury\ObjectRouterBundle\RoutingService
    object_router.redirect.class: Nercury\ObjectRouterBundle\RedirectService
    object_router.generator.class: Nercury\ObjectRouterBundle\GeneratorService
    twig.extension.object_router.class: Nercury\ObjectRouterBundle\Twig\ObjectRouteExtensions
    object_router.configuration: ~

services:
    object_router.routing:
        class: %object_router.routing.class%
        arguments: [ %object_router.configuration%, "@logger", "@doctrine", "@router"]
        calls:
          - [ setKernel, [ "@kernel" ] ]
          
    object_router.redirect:
        class: %object_router.redirect.class%
        arguments: [ %object_router.configuration% ]
        calls:
          - [ setObjectRouter, [ "@object_router.routing" ] ]
          - [ setDoctrine, [ "@doctrine" ] ]
          
    object_router.generator:
        class: %object_router.generator.class%
        arguments: [ %object_router.configuration%, "@logger", "@doctrine", "@router" ]
        calls:
          - [ setKernel, [ "@kernel" ] ]
          - [ setObjectRouter, [ "@object_router.routing" ] ]
          
    twig.extension.object_router:
        class: %twig.extension.object_router.class%
        arguments: [ "@object_router.routing" ]
        public: false
        tags: 
          - { name: twig.extension }
