parameters:
    object_router.class: Nercury\ObjectRouterBundle\RoutingService
    object_router.configuration: ~

services:
    object_router:
        class: %object_router.class%
        scope: request
        arguments: [ %object_router.configuration%, "@logger", "@doctrine", "@router", "@request" ]
        calls:
          - [ setKernel, [ "@kernel" ] ]
          
        