parameters:
    object_router.class: Nercury\ObjectRouterBundle\ObjectRouterService
    object_router.configuration: ~

services:
    object_router:
        class: %object_router.class%
        arguments: [ %object_router.configuration%, "@logger", "@doctrine", "@router", "@session" ]
        